org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.10
forge_version_range=[47,)
loader_version_range=[47,)


## Mod Properties
mod_id=chinesedelight
mod_name=Chinese Delight
mod_license=MIT
mod_version=1.20.1-0.0.1
mod_group_id=aysta.ChineseDelight
mod_authors=Aysta3045
mod_description=More Chinese Foods.\n\nThanks all partners in gitee and github\ngitee:https://gitee.com/aysta3045/ChineseDelight\ngithub:https://github.com/aysta3045/ChineseDelight

## mod
jei_version=15.0.0.12
#farmers_delight_file_id=6917255
